# Site
url: "https://developeri.sh"
name: "Developer.ish"
author_byline: "by Brandon Him"
description: "Think in products, build with systems, ship with AI"
meta_description: "Think in products, build with systems, ship with AI"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
google_analytics: 'UA-46278016-1'
disqus: 'brandonhim'

# Authors
authors:
  brandon:
    name: Brandon
    display_name: Brandon Him
    description: "Solutions Engineering at Apollo GraphQL. Ex-Okta, Ex-Cisco."
    gravatar: 49a4f5377b60e3fcc194ca4a9c7ffb00
    email: brandonhim@live.com
    web: https://developeri.sh
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
